### ISSUE TITLE
'edit' slug not translated

### ISSUE THREAD

**Issue by vddgil** [museways/translatable_routes#1]
Hello,

I have the following yml in my application:

```

fr:
  routes:
    edit: modification
    new: nouveau
    users: utilisateurs
    sign_in: connexion
    sign_up: creer-un-compte
    password: mot-de-passe
    facebook_registration: inscription-facebook
    profile: profil
    sign_out: deconnexion
    student_rooms: kots
```

The 'new' slug is translated correctly, bu the 'edit' one is not. Home can you explain that ? 

Thanks in advance,

Gil
